import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Script from "next/script";
import { siteConfig } from "@/config/site-config";

/**
 * SEO METADATA CONFIGURATION
 * 
 * This metadata is pulled from siteConfig to ensure consistency.
 * For template users: Update the seo object in /config/site-config.ts
 * DO NOT edit this file directly for basic customization.
 * 
 * Advanced users: You can override specific fields here if needed.
 */
export const metadata: Metadata = {
  title: siteConfig.seo.title,
  description: siteConfig.seo.description,
  keywords: siteConfig.seo.keywords,
  authors: siteConfig.seo.authors,
  creator: siteConfig.seo.creator,
  openGraph: {
    type: siteConfig.seo.openGraph.type,
    locale: siteConfig.seo.openGraph.locale,
    url: siteConfig.seo.openGraph.url,
    title: siteConfig.seo.openGraph.title,
    description: siteConfig.seo.openGraph.description,
    siteName: siteConfig.seo.openGraph.siteName,
    images: siteConfig.seo.openGraph.images,
  },
  twitter: {
    card: siteConfig.seo.twitter.card,
    title: siteConfig.seo.twitter.title,
    description: siteConfig.seo.twitter.description,
    images: siteConfig.seo.twitter.images,
    creator: siteConfig.seo.twitter.creator,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Add verification codes from config (optional)
  ...(siteConfig.seo.verification && {
    verification: siteConfig.seo.verification,
  }),
  // Set canonical URL
  alternates: {
    canonical: siteConfig.seo.canonical,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased">
        {children}

        {/* Structured Data: Directly connects your portfolio to your LinkedIn and GitHub */}
        <Script
          id="structured-data"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              name: "Mehak Fatima Naqvi",
              alternateName: "miss-kniz",
              url: "https://mehak-naqvi.vercel.app",
              image:
                "https://mehak-naqvi.vercel.app/photo-gallery/portfolio.jpg",
              jobTitle: "Full-Stack Developer",
              worksFor: {
                "@type": "Organization",
                name: "ThinkBuildSol",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "Faisalabad",
                addressCountry: "PK",
              },
              sameAs: [
                "https://www.linkedin.com/in/miss-kniz",
                "https://github.com/miss-kniz",
              ],
              description:
                "Full-stack developer specializing in PostgreSQL, Express, React, and Next.js (PERN stack).",
            }),
          }}
        />
      </body>
    </html>
  );
}
